name: CI

on:
  # Trigger the workflow on push or pull requests, but only for the
  # main branch
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
  
jobs:
  msbuild:
    runs-on: 'windows-latest'
    steps:
    - name: Checkout open-sysmon-conf
      uses: actions/checkout@v2
    
    - name: Download Sysmon 
      run: Invoke-WebRequest http://live.sysinternals.com/tools/sysmon.exe -OutFile .\sysmon.exe
      shell: powershell
    
    - name: Run Sysmon 
      run: .\sysmon.exe -accepteula -i sysmonconfig-export.xml
      shell: powershell
      
    - name: Check Eventcount
      run:  '$EventCount = 0 ;Get-WinEvent -ListLog Microsoft-Windows-Sysmon* | where {$_.RecordCount -gt 0} | foreach{$_;$EventCount = $EventCount + $_.RecordCount}|Out-Null;"Eventcount: "+$EventCount; if ($EventCount -gt 50){ Write-Output "Too many events"; $host.SetShouldExit(1)}'
      shell: powershell
      
  busySystem:
    runs-on: 'windows-latest'
    steps:
    - name: Checkout open-sysmon-conf
      uses: actions/checkout@v2
    
    - name: Download Sysmon 
      run: Invoke-WebRequest http://live.sysinternals.com/tools/sysmon.exe -OutFile .\sysmon.exe
      shell: powershell
      
    - name: Run Sysmon 
      run: .\sysmon.exe -accepteula -i sysmonconfig-export.xml
      shell: powershell
      
    - name: Print Eventcount
      run: Get-WinEvent -ListLog Microsoft-Windows-Sysmon*
      
    - name: Install some Choco Packages
      run: choco install ninja adobereader googlechrome firefox jre8 notepadplusplus.install vlc python3 dotnetfx openssh winrar nodejs.install foxitreader autohotkey.portable putty.install skype ccleaner winlogbeat gimp
    
    - name: Check Eventcount
      run:  '$EventCount = 0 ;Get-WinEvent -ListLog Microsoft-Windows-Sysmon* | where {$_.RecordCount -gt 0} | foreach{$_;$EventCount = $EventCount + $_.RecordCount}|Out-Null;"Eventcount: "+$EventCount; if ($EventCount -gt 10000){ Write-Output "Too many events"; $host.SetShouldExit(1)}'
      shell: powershell
